version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-bigassistant
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # --- TAMBAHKAN BAGIAN INI ---
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ----------------------------
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    restart: unless-stopped

volumes:
  n8n_data: